Fix: hover height value and Add: social links
Reactv4/awesome-business-cards-v4 pull request #37
Opened 2024-01-25 19:21 UTC by ChamithSkulathunga

Check my pull request

2024-01-28 16:38 UTC, radika-insfra requested changes

2024-01-28 16:38 UTC, radika-insfra commented on R4145/index.html
> +                <a href="https://www.linkedin.com/in/chamith-sadeepa-kulathung" target="_blank" class="hr">LinkdIn</a>
You're used a class name called hr. but it seems that there is no .hr class styles.

2024-01-28 16:38 UTC, radika-insfra commented on R4145/index.html
> +                <a href="https://www.behance.net/chamithsadeepa1" target="_blank" class="h">Behance</a>
usually we don't use a single letter for class names. since it will make confusions with element selectors. 

.p
p

2024-01-29 15:31 UTC, ChamithSkulathunga commented
ok It was my mistake. I'll fix it. I want to know, after I fix it, what I'm doing again.

2024-01-30 06:03 UTC, radika-insfra commented
> ok It was my mistake. I'll fix it. I want to know, after I fix it, what I'm doing again.

after fixing them. you just need to commit and push your changes. it will automatically update the PR.

2024-02-04 07:30 UTC, ChamithSkulathunga commented
Sir, I've fixed these errors. Can you check this ?

2024-02-04 07:32 UTC, radika-insfra commented
> Sir, I've fixed these errors. Can you check this ?

suer. I'll check. thank you.

2024-02-12 19:02 UTC, radika-insfra approved these changes
Great work

2024-02-12 19:02 UTC, merged